services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ./data/ollama:/root/.ollama
      - ./ollama/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
  gradio:
    build:
      context: ./gradio
      dockerfile: Dockerfile
    container_name: gradio
    ports:
      - 7860:7860
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
    command: ["python", "app.py"]
    depends_on:
      - ollama
